### ISSUE TITLE
Thrustmaster TMX GIP Racing Wheel

### ISSUE THREAD

**Issue by wurcyc** [emtek995/TMX-driver#1]
when I migrate your driver to linux system and we use below thrustmaster product
https://shop.thrustmaster.com/en_gb/tmx-pro-force-feedback.html
below function can be executed

static int **tmx_probe**(struct usb_interface *iface, const struct usb_device_id *id)
{
    .....
}

, but the function **hid_tmx_probe** is not excuted.
static int hid_tmx_probe(struct hid_device *hdev, const struct hid_device_id *id)
{
....
}
and it means the pid is not changed from **0xB67E** to **0xB65D**?
Please help check:-)

**Comment by emtek995** [comment]
I forgot to add into my README that you also need do blacklist the hid-thrustmaster and hid-tmff kernel modules. This will make other thrustmaster wheels to be not detected.
