### ISSUE TITLE
make install breaks kernel module loading

### ISSUE THREAD

**Issue by pastaq** [emtek995/TMX-driver#6]
Loading the driver with insmod works well. However; if I install the driver with the included make file my system will fail to load any kernel modules on the next boot. This effectively bricks the system as not even the keyboard driver will load and I am left in an emergency console with no input devices to even do a recovery. I've confirmed this twice after reinstalling the OS.

OS: EndeavourOS
Kernel: 6.6.4-arch-1

steps to reproduce:

```
cd ~/TMX-driver
make
sudo make install
reboot
```

Any idea how I can avoid this in the future? EndeavourOS uses dracut for initcpio.

**Comment by emtek995** [comment]
Use dkms to install the module.
